local_backend: true

backend:
  name: gitea
  app_id: bf2506c8-ea2f-40c8-b315-59b39c02e7ae
  api_root: https://health.joanneum.at/git/api/v1
  base_url: https://health.joanneum.at/git
  auth_endpoint: https://health.joanneum.at/git/login/oauth/authorize
  branch: main
  repo: PreNudge/prenudge-health-profile


#publish_mode: editorial_workflow   # The Gitea backend does not support editorial workflow.

media_folder: media
public_folder: /media

i18n:
  structure: single_file            # 'single_file' speichert de und en zusammen in einer JSON-Datei.
  locales: [de, en]
  default_locale: de

collections:

  - name: subject-areas
    label: Subject Areas
    label_singular: "Subject Area"
    folder: hp-subject-areas
    create: true                    # Damit der 'Erstellen Button' angezeigt wird.
    i18n: true                      # Aktiviert i18n für diese gesamte Collection
    extension: json                 # Erzwingt die Endung .json statt .md
    format: json                    # Sagt dem CMS, dass es JSON-Daten schreiben soll
    slug: "{{id_tech}}"             # Dateiname wird die technische ID

    fields:
      - label: Template             # Damit in jedem JSON File erkennbar ist, von welchem Typ/Template es ist.
        name: template
        widget: hidden
        default: subject-area
        i18n: duplicate             # 'duplicate' kopiert den Wert von 'de' nach 'en',

      - label: "Technische ID"
        name: id_tech
        widget: id_tech_auto
        i18n: duplicate
        pattern: ['^[a-z0-9\-]+$', "Nur Kleinbuchstaben, Zahlen und Bindestriche erlaubt"]

      - label: Title
        name: title
        widget: string
        i18n: translate # falls 'en' noch leer ist (gut für technische Werte).
        required: true

      - label: Description
        name: description
        required: false
        widget: markdown
        i18n: translate # 'translate' Feld muss ueberesetzt werden


  - name: categories
    label: Categories
    label_singular: "Category"
    folder: hp-categories
    create: true
    i18n: true
    extension: json
    format: json
    slug: "{{id_tech}}"
    summary: "{{title}} [{{subject-area}}]"

    fields:
      - label: Template
        name: template
        widget: hidden
        default: category
        i18n: duplicate

      - label: "Technische ID"
        name: id_tech
        widget: string
        i18n: duplicate

      - label: Subject Area
        name: subject-area
        widget: relation
        collection: subject-areas
        search_fields: [id_tech, title, description]
        value_field: id_tech
        display_fields: ["{{title}} - {{id_tech}}"]
        i18n: duplicate

      - label: Title
        name: title
        widget: string
        i18n: translate

      - label: Description
        name: description
        required: false
        widget: markdown
        i18n: translate

  - label: Indicator Dimensions
    name: dimensions
    label_singular: "Indicator Dimension"
    folder: hp-dimensions
    create: true
    i18n: true
    extension: json
    format: json
    slug: "{{id_tech}}"
    summary: "{{title}} [{{category}}]"
    fields:
      - label: Template
        name: template
        widget: hidden
        default: dimension
        i18n: duplicate

      - label: "Technische ID"
        name: id_tech
        widget: string
        i18n: duplicate

      - label: Category
        name: category
        widget: relation
        collection: categories
        search_fields: [id_tech, title, description]
        value_field: id_tech
        display_fields: ["{{title}} - {{id_tech}}"]
        i18n: duplicate

      - label: Title
        name: title
        widget: string
        i18n: translate

      - label: Description
        name: description
        required: false
        widget: markdown
        i18n: translate

  - name: observations
    label: Observations
    label_singular: "Observation"
    folder: hp-observations
    create: true
    i18n: true
    extension: json
    format: json
    slug: "{{id_tech}}"
    summary: "{{title}} [{{dimension}}] [{{category}}]"
    fields:
      - label: Template
        name: template
        widget: hidden
        default: observation
        i18n: duplicate

      - label: "Technische ID"
        name: id_tech
        widget: string
        i18n: duplicate

      - label: Indicator Dimension
        name: dimension
        widget: relation
        collection: dimensions
        search_fields: [id_tech, title, description]
        value_field: id_tech
        display_fields: ["{{title}} - {{id_tech}}"]
        i18n: duplicate

      - label: Category
        name: category
        widget: relation
        collection: categories
        search_fields: [id_tech, title, description]
        value_field: id_tech
        display_fields: ["{{title}} - {{id_tech}}"]
        i18n: duplicate

      - label: Title
        name: title
        widget: string
        i18n: translate

      - label: Unit
        name: unit
        widget: string
        i18n: translate

      - label: Data Format
        name: data_format
        widget: select
        i18n: duplicate
        options:
          - label: Numeric (float)
            value: numeric
          - label: Integer
            value: integer
          - label: Categorical
            value: categorical
          - label: Boolean
            value: boolean
          - label: Date
            value: date
          - label: Time
            value: time
          - label: DateTime
            value: datetime
          - label: Text
            value: text
          - label: Percentage
            value: percentage
          - label: Score / Index
            value: score

      - label: Specific norms
        name: specific-norms
        required: false
        widget: markdown
        i18n: translate

      - label: "Source/References"
        name: source
        default: "Scientific publication, guideline, or official recommendation underpinning the measurement instrument (e.g., WHO guidelines, NIH toolkit)"
        required: false
        widget: markdown
        i18n: translate


  - name: observation-sources
    label: "Observation Sources"
    label_singular: "Observation Source"
    folder: hp-observation-sources
    create: true
    i18n: true
    extension: json
    format: json
    slug: "{{id_tech}}"
    summary: "{{title}} [{{observation}}]"
    fields:
      - label: Template
        name: template
        widget: hidden
        default: observation-source
        i18n: duplicate
      - label: "Technische ID"
        name: id_tech
        widget: string
        i18n: duplicate
      - label: Observation
        name: observation
        widget: relation
        collection: observations
        search_fields: [id_tech, title, description]
        value_field: id_tech
        display_fields: ["{{title}} - {{id_tech}}"]
        i18n: duplicate
      - label: Title
        name: title
        widget: string
        i18n: translate
      - label: Description
        name: description
        required: false
        widget: markdown
        i18n: translate
      - label: Source Type
        name: source-type
        widget: select
        options: ["device", "questionnaire"]
        i18n: duplicate
      - label: Frequency
        name: frequency
        widget: text
        i18n: translate
      - label: FHIR-IG
        name: fhir-ig
        required: false
        widget: object
        i18n: true
        fields:
          - label: "Display"
            name: display
            widget: text
            i18n: translate
          - label: "URL"
            name: url
            widget: string
            i18n: duplicate
